stages:
    - test

variables:
    SRCDIR: /go/src/github.com/go-kivik/pouchdb
    COUCHDB_USER: admin
    COUCHDB_PASSWORD: abc123
    KIVIK_TEST_DSN_COUCH23: http://admin:abc123@couch23:5984/

.test: &test_template
    image: golang:1.12
    stage: test
    services:
        - name: apache/couchdb:2.3.1
          alias: couch23
    before_script:
        - ./script/complete_couch2.sh ${KIVIK_TEST_DSN_COUCH23}
    script:
        - go get golang.org/dl/go1.12.16
        - go1.12.16 download
        - mkdir -p $(dirname ${SRCDIR})
        - ln -s ${CI_PROJECT_DIR} ${SRCDIR}
        - cd ${SRCDIR}
        - curl -sL https://deb.nodesource.com/setup_${NODE_VER}.x | bash -
        - apt-get update -qq && apt-get install -y nodejs
        - cp "$NPM_PROFILE" package.json
        - npm install
        - GO111MODULE=off go get -u github.com/gopherjs/gopherjs
        - npm install source-map-support
        - |
            (
                cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
                npm install --global node-gyp
                node-gyp rebuild
                mkdir -p ~/.node_libraries/
                cp build/Release/syscall.node ~/.node_libraries/syscall.node
            )
        - curl https://glide.sh/get | sh
        - glide update
        - ./script/test_version.sh
        - GOPHERJS_GOROOT="$(go1.12.16 env GOROOT)" gopherjs test $(go list ./... | grep -v /vendor/ | grep -Ev 'kivik/(serve|auth|proxy)')

pouchdb6:
    <<: *test_template
    variables:
        NODE_VER: 10
        NPM_PROFILE: pouchdb6-package.json

pouchdb7:
    <<: *test_template
    variables:
        NODE_VER: 12
        NPM_PROFILE: pouchdb7-package.json

lint:
    stage: test
    image: golang:1.12
    services: []
    before_script:
        - ''
    script:
        - mkdir -p $(dirname ${SRCDIR})
        - ln -s ${CI_PROJECT_DIR} ${SRCDIR}
        - cd ${SRCDIR}
        - curl https://glide.sh/get | sh
        - glide update
        - go get -u github.com/gopherjs/gopherjs
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
        - golangci-lint run ./...
