dist: trusty
sudo: required
services:
    - docker
cache:
    directories:
        - node_modules
        - $HOME/gopath/pkg
        - /var/lib/docker
language: go
os:
    - linux
    - osx
go:
    - 1.9.x
addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide
env:
    global:
        - KIVIK_TEST_DSN_COUCH21="http://admin:abc123@localhost:6002/"
        - HOMEBREW_NO_AUTO_UPDATE=1
    matrix:
        - MODE=standard

matrix:
    allow_failures:
        - go: master

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
